[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "ipykernel>=6.27.1",
    "pandas>=2.1.3",
    "geopy>=2.4.1",
    "plotly>=5.18.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

